"""Build the manuscript: numbers.json + templates -> paper/paper.html, paper/supplement.html -> PDF (fitz.Story).
Every number in the text and tables is taken from paper/numbers.json (generated by paper/extract_numbers.py)."""
import json, sys, os, re, datetime
sys.path.insert(0, '.')
import fitz
from jinja2 import Environment, FileSystemLoader

N = json.load(open('paper/numbers.json'))
def _intkeys(d):
    return {(int(k) if isinstance(k, str) and k.lstrip('-').isdigit() else k): v for k, v in d.items()}
for k in N['spaces']: N['spaces'][k] = _intkeys(N['spaces'][k])
for k in N['lexicon']: N['lexicon'][k] = _intkeys(N['lexicon'][k])
for k in N['entropy']: N['entropy'][k]['twins'] = _intkeys(N['entropy'][k]['twins'])
N['text_vs_image']['positive_control'] = _intkeys(N['text_vs_image']['positive_control'])
for k in N['section_within_hand']: N['section_within_hand'][k]['rows'] = _intkeys(N['section_within_hand'][k]['rows'])
def f(x, d=3):
    return ('%.' + str(d) + 'f') % x
def pct(x, d=1):
    return ('%.' + str(d) + 'f') % (100 * x) + '%'
def sgn(x, d=3):
    return ('%+.' + str(d) + 'f') % x

# ---------------------------------------------------------------- formatted values used in prose
v = {}
c = N['corpus']; v.update(pages_P=c['pages_P'], lines_P=f"{c['lines_P']:,}", tokens_P=f"{c['tokens_P']:,}", pages_total=c['pages_total'], lines_total=f"{c['lines_total']:,}", labels_L=f"{c['labels_L']:,}")
b = N['basic']
v.update(types_all=f"{b['VMS all (P)']['types']:,}", tokens_all=f"{b['VMS all (P)']['tokens']:,}", ttr_all=f(b['VMS all (P)']['ttr']), hapax_all=f(b['VMS all (P)']['hapax'], 2), wlen_all=f(b['VMS all (P)']['wlen'], 2),
         h1_all=f(b['VMS all (P)']['h1'], 2), h2_all=f(b['VMS all (P)']['h2'], 2), ratio_all=f(b['VMS all (P)']['h2'] / b['VMS all (P)']['h1'], 2), zipf_all=f(b['VMS all (P)']['zipf'], 2))
ratios = {k: b[k]['h2'] / b[k]['h1'] for k in b}
v.update(ratio_lang_min=f(min(ratios[k] for k in ('de_faust (chunk)', 'it_dante (chunk)', 'la_caesar (chunk)', 'en_tolstoy (chunk)', 'he_genesis')), 2),
         ratio_lang_max=f(max(ratios[k] for k in ('de_faust (chunk)', 'it_dante (chunk)', 'la_caesar (chunk)', 'en_tolstoy (chunk)', 'he_genesis')), 2))
p = N['proj']
v.update(edge=f(p['VMS c=jn']['l1f1']), tok=f(p['VMS c=jn']['word']), edge2=f(p['VMS c=jn']['l2f2']), edgeB=f(p['VMSB c=jn']['l1f1']), tokB=f(p['VMSB c=jn']['word']), edgeA=f(p['VMSA c=jn']['l1f1']), tokA=f(p['VMSA c=jn']['word']),
         edge_sp=f(p['VMS c=sp']['l1f1']), tok_sp=f(p['VMS c=sp']['word']),
         edge_la=f(p['Latin']['l1f1']), tok_la=f(p['Latin']['word']), edge_de=f(p['German']['l1f1']), tok_de=f(p['German']['word']), edge_he=f(p['Hebrew']['l1f1']), tok_he=f(p['Hebrew']['word']), edge_it=f(p['Italian']['l1f1']), tok_it=f(p['Italian']['word']),
         l2f2_la=f(p['Latin']['l2f2']), l2f2_he=f(p['Hebrew']['l2f2']))
e = N['ed_buckets_withinline']; v.update(edw0=f(e['ed0']), edw1=f(e['ed1']), edw2=f(e['ed2']), edw3=f(e['ed3']))
g = N['pmi_global']; v.update(pg_tot=f(g['VMS raw']['total']), pg_ed3=f(g['VMS raw']['ed3']), pg_la_tot=f(g['Latin']['total']), pg_la_ed3=f(g['Latin']['ed3']), pg_de_ed3=f(g['German']['ed3']), pg_it_ed3=f(g['Italian']['ed3']), pg_it_ed2=f(g['Italian']['ed2']))
lu = N['lineunit']
v.update(lu_across=f(lu['VMS none']['across']), lu_within=f(lu['VMS none']['within']), lu_within_sd=f(lu['VMS none']['within_sd']), lu_n=f"{lu['VMS none']['n']:,}",
         lu_across_l=f(lu['VMS light']['across']), lu_within_l=f(lu['VMS light']['within']),
         lu_la_across=f(lu['Latin']['across']), lu_la_within=f(lu['Latin']['within']), lu_it_across=f(lu['Italian']['across']), lu_it_within=f(lu['Italian']['within']), lu_de_across=f(lu['German']['across']), lu_de_within=f(lu['German']['within']),
         lu_A_across=f(lu['VMS-A light']['across']), lu_A_within=f(lu['VMS-A light']['within']), lu_B_across=f(lu['VMS-B light']['across']), lu_B_within=f(lu['VMS-B light']['within']))
ed = N['edges']
v.update(cb_lf=f(ed['VMS raw']['combo']['last_k -> first_k+1']['mi']), cb_mm=f(ed['VMS raw']['combo']['mid_k -> mid_k+1']['mi']), cb_ff=f(ed['VMS raw']['combo']['first_k -> first_k+1']['mi']), cb_ll=f(ed['VMS raw']['combo']['last_k -> last_k+1']['mi']),
         cb_la_lf=f(ed['Latin (chunked)']['combo']['last_k -> first_k+1']['mi']), cb_it_lf=f(ed['Italian (chunked)']['combo']['last_k -> first_k+1']['mi']),
         pos_first=f(ed['VMS raw']['pos']['first']['mi']), pos_mid=f(ed['VMS raw']['pos']['middle']['mi']), pos_last=f(ed['VMS raw']['pos']['last']['mi']), pos_last_ttr=f(ed['VMS raw']['pos']['last']['ttr']), pos_mid_ttr=f(ed['VMS raw']['pos']['middle']['ttr']),
         pos_la_max=f(max(ed['Latin (chunked)']['pos'][k]['mi'] for k in ed['Latin (chunked)']['pos'])))
s = N['spaces']
v.update(sp_k1=pct(s['VMS c=jn'][1]['gain']), sp_k1_f1=f(s['VMS c=jn'][1]['F1'], 2), sp_k2=pct(s['VMS c=jn'][2]['gain']), sp_k2_f1=f(s['VMS c=jn'][2]['F1'], 2),
         sp_la1=pct(s['Latin'][1]['gain']), sp_la2=pct(s['Latin'][2]['gain']), sp_it1=pct(s['Italian'][1]['gain']), sp_de1=pct(s['German'][1]['gain']), sp_he1=pct(s['Hebrew'][1]['gain']), sp_he2=pct(s['Hebrew'][2]['gain']),
         sp_rule1=pct(s['Latin rule-spaced'][1]['gain']), sp_rule1_f1=f(s['Latin rule-spaced'][1]['F1'], 2), sp_A1=pct(s['VMS-A c=jn'][2]['gain']), sp_B1=pct(s['VMS-B c=jn'][2]['gain']),
         sp_lang_min=pct(min(s[k][1]['gain'] for k in ('Latin', 'Italian', 'German', 'Hebrew'))), sp_lang_max=pct(max(s[k][1]['gain'] for k in ('Latin', 'Italian', 'German', 'Hebrew'))))
lx = N['lexicon']
v.update(lx_real=f(lx['VMS'][2]['tok_real'], 2), lx_syn=f(lx['VMS'][2]['tok_synth'], 2), lx_real_t=f(lx['VMS'][2]['typ_real'], 2), lx_syn_t=f(lx['VMS'][2]['typ_synth'], 2), lx_real3=f(lx['VMS'][3]['tok_real'], 2), lx_syn3=f(lx['VMS'][3]['tok_synth'], 2),
         lx_la=f(lx['Latin'][2]['tok_real'], 2), lx_la_s=f(lx['Latin'][2]['tok_synth'], 2), lx_la_t=f(lx['Latin'][2]['typ_real'], 2), lx_la_ts=f(lx['Latin'][2]['typ_synth'], 2),
         lx_de_s=f(lx['German'][2]['tok_synth'], 2), lx_de=f(lx['German'][2]['tok_real'], 2), lx_it_s=f(lx['Italian'][2]['tok_synth'], 2), lx_it=f(lx['Italian'][2]['tok_real'], 2), lx_he_s=f(lx['Hebrew'][2]['tok_synth'], 2), lx_he=f(lx['Hebrew'][2]['tok_real'], 2),
         lx_rule=f(lx['Latin rule msty'][2]['tok_real'], 2), lx_rule_s=f(lx['Latin rule msty'][2]['tok_synth'], 2), lx_bis=f(lx['Latin bisyl'][2]['tok_real'], 2), lx_bis_s=f(lx['Latin bisyl'][2]['tok_synth'], 2),
         lx_A=f(lx['VMS A'][2]['tok_real'], 2), lx_A_s=f(lx['VMS A'][2]['tok_synth'], 2), lx_B=f(lx['VMS B'][2]['tok_real'], 2), lx_B_s=f(lx['VMS B'][2]['tok_synth'], 2))
ep = N['entropy']
def tw(name, order=3): return ep[name]['twins'][order]
v.update(ep_h=[f(x, 2) for x in ep['VMS all']['real']], ep_d3=sgn(ep['VMS all']['real'][2] - tw('VMS all')['h'][2], 2), ep_d4=sgn(ep['VMS all']['real'][3] - tw('VMS all')['h'][3], 2), ep_d5=sgn(ep['VMS all']['real'][4] - tw('VMS all')['h'][4], 2),
         ep_la_d4=sgn(ep['Latin']['real'][3] - tw('Latin')['h'][3], 2), ep_la_d5=sgn(ep['Latin']['real'][4] - tw('Latin')['h'][4], 2), ep_it_d4=sgn(ep['Italian']['real'][3] - tw('Italian')['h'][3], 2), ep_de_d4=sgn(ep['German']['real'][3] - tw('German')['h'][3], 2), ep_he_d4=sgn(ep['Hebrew']['real'][3] - tw('Hebrew')['h'][3], 2),
         ep_lz=f(ep['VMS all']['lzma'], 2), ep_lz_tw=f(tw('VMS all')['lzma'], 2), ep_la_lz=f(ep['Latin']['lzma'], 2), ep_la_lz_tw=f(tw('Latin')['lzma'], 2))
m = N['mech']
def M(k, col, d=3): return f(m[k][col], d)
v.update(mk_edge3=M('markov3+drift', 'edge_mi'), mk_tok3=M('markov3+drift', 'token_mi'), mk_res3=sgn(m['markov3+drift']['lzma_resid']), mk_res4=sgn(m['markov4+drift']['lzma_resid']), vms_res=sgn(m['VMS']['lzma_resid']), vms_page=M('VMS', 'page_mi'), mk_page3=M('markov3+drift', 'page_mi'),
         mk_hap3=M('markov3+drift', 'hapax', 2), mk_hap4=M('markov4+drift', 'hapax', 2), mk_tok4=M('markov4+drift', 'token_mi'), vms_tok=M('VMS', 'token_mi'), vms_adj=M('VMS', 'adj_mi_same_n'), mk_adj4=M('markov4+drift', 'adj_mi_same_n'),
         hier_edge=M('hier o4 lam0.5', 'edge_mi'), hier_tok=M('hier o4 lam0.5', 'token_mi'), hier_page=M('hier o4 lam0.5', 'page_mi'), hier_res=sgn(m['hier o4 lam0.5']['lzma_resid']), hier_hap=M('hier o4 lam0.5', 'hapax', 2), hier_lexs=M('hier o4 lam0.5', 'lex_synth', 2), hier_lexr=M('hier o4 lam0.5', 'lex_real', 2),
         la_res=sgn(m['latin']['lzma_resid']), la_rule_res=sgn(m['latin rule-sp']['lzma_resid']), rugg_edge=M('rugg grille', 'edge_mi'), rugg_tok=M('rugg grille', 'token_mi'), rugg_res=sgn(m['rugg grille']['lzma_resid']), rugg_hap=M('rugg grille', 'hapax', 2),
         ts_edge=M('timm-schinner v2', 'edge_mi'), ts_res=sgn(m['timm-schinner v2']['lzma_resid']), ts_space=pct(m['timm-schinner v2']['space_gain']), ts_lexs=M('timm-schinner v2', 'lex_synth', 2), ts_lexr=M('timm-schinner v2', 'lex_real', 2), ts_page=M('timm-schinner v2', 'page_mi'),
         vb_edge=M('verbose+indep', 'edge_mi'), vb_tok=M('verbose+indep', 'token_mi'), vb_hap=M('verbose+indep', 'hapax', 2), vb_res=sgn(m['verbose+indep']['lzma_resid']),
         ak1_edge=M('autokey 1g/letter', 'edge_mi'), ak1_space=pct(m['autokey 1g/letter']['space_gain']), ak1_lexr=M('autokey 1g/letter', 'lex_real', 2), ak1_lexs=M('autokey 1g/letter', 'lex_synth', 2), ak1_res=sgn(m['autokey 1g/letter']['lzma_resid']), ak2_res=sgn(m['autokey 2g/letter']['lzma_resid']), ak2_edge=M('autokey 2g/letter', 'edge_mi'),
         nb_edge=M('naibbe indep, card/letter', 'edge_mi'), nb_tok=M('naibbe indep, card/letter', 'token_mi'), nb_space=pct(m['naibbe indep, card/letter']['space_gain']), nb_hap=M('naibbe indep, card/letter', 'hapax', 2), nb_zipf=M('naibbe indep, card/letter', 'zipf', 2), nb_lexr=M('naibbe indep, card/letter', 'lex_real', 2), nb_lexs=M('naibbe indep, card/letter', 'lex_synth', 2),
         nb_h2=M('naibbe indep, card/letter', 'h2', 2), nb_h4=M('naibbe indep, card/letter', 'h4', 2), nb_res=sgn(m['naibbe indep, card/letter']['lzma_resid']), nb_page=M('naibbe indep, card/letter', 'page_mi'), nb_run_res=sgn(m['naibbe running']['lzma_resid']), nb_it_res=sgn(m['naibbe running Italian']['lzma_resid']), nb_run_brk=M('naibbe running', 'break_mi'), nb_types=f"{m['naibbe indep, card/letter']['types']:,}",
         ns6_edge=M('naibbe stateful w=0.6 c=0.15', 'edge_mi'), ns6_tok=M('naibbe stateful w=0.6 c=0.15', 'token_mi'), ns6_res=sgn(m['naibbe stateful w=0.6 c=0.15']['lzma_resid']),
         ns9_edge=M('naibbe stateful w=0.9 c=0.15', 'edge_mi'), ns9_tok=M('naibbe stateful w=0.9 c=0.15', 'token_mi'), ns9_res=sgn(m['naibbe stateful w=0.9 c=0.15']['lzma_resid']),
         ns10_edge=M('naibbe stateful w=1.0 c=0.05', 'edge_mi'), ns10_tok=M('naibbe stateful w=1.0 c=0.05', 'token_mi'), ns10_res=sgn(m['naibbe stateful w=1.0 c=0.05']['lzma_resid']), ns_hap=M('naibbe stateful w=0.9 c=0.15', 'hapax', 2),
         li_edge=M('latin indep lines', 'edge_mi'), li_brk=M('latin indep lines', 'break_mi'), li_tok=M('latin indep lines', 'token_mi'), la_brk=M('latin', 'break_mi'), vms_brk=M('VMS', 'break_mi'), vms_edge_b=M('VMS', 'edge_mi'),
         vms_hap=M('VMS', 'hapax', 2), vms_space=pct(m['VMS']['space_gain']), vms_lexr=M('VMS', 'lex_real', 2), vms_lexs=M('VMS', 'lex_synth', 2), vms_types=f"{m['VMS']['types']:,}", vms_tokens=f"{m['VMS']['tokens']:,}")
r = N['robust']
v.update(oos3=sgn(r['oos_order3']['resid']), oos4=sgn(r['oos_order4']['resid']), oos_rev=sgn(r['oos_reversed']['resid']), oos_h3=sgn(r['oos_order3']['h3']), oos_h3b=sgn(r['oos_order4']['h3']), oos_h3c=sgn(r['oos_reversed']['h3']),
         ho_edge=f(r['held-out real (even pages)']['edge']), tw_edge=f(r['twin from odd-page model']['edge']), ho_tok=f(r['held-out real (even pages)']['token']), tw_tok=f(r['twin from odd-page model']['token']), ho_page=f(r['held-out real (even pages)']['page']), tw_page=f(r['twin from odd-page model']['page']),
         ho_hap=f(r['held-out real (even pages)']['hapax'], 2), tw_hap=f(r['twin from odd-page model']['hapax'], 2), ho_space=pct(r['held-out real (even pages)']['space']), tw_space=pct(r['twin from odd-page model']['space']),
         h1_edge=f(r['hand 1 (112 pages)']['edge']), h2_edge=f(r['hand 2 (46 pages)']['edge']), h3_edge=f(r['hand 3 (31 pages)']['edge']), A_edge=f(r['Currier A']['edge']), B_edge=f(r['Currier B']['edge']),
         lexgap_max_hands=f(max(abs(r[k]['lex_real'] - r[k]['lex_synth']) for k in r if k.startswith('hand') or k.startswith('Currier')), 2))
t = N['transcriptions']
v.update(it_edge=f(t['IT2a jn']['edge']), it_tok=f(t['IT2a jn']['token']), it_brk=f(t['IT2a jn']['brk']), it_space=pct(t['IT2a jn']['space']), it_hap=f(t['IT2a jn']['hapax'], 2), it_lexr=f(t['IT2a jn']['lex_real'], 2), it_lexs=f(t['IT2a jn']['lex_synth'], 2), it_res=sgn(t['IT2a jn']['resid']), it_page=f(t['IT2a jn']['page']), it_tokens=f"{t['IT2a jn']['tokens']:,}", it_types=f"{t['IT2a jn']['types']:,}",
         zl_sp_edge=f(t['ZL3b sp']['edge']), zl_sp_tok=f(t['ZL3b sp']['token']), zl_sp_hap=f(t['ZL3b sp']['hapax'], 2), zl_sp_tokens=f"{t['ZL3b sp']['tokens']:,}")
d = N['drift']
v.update(dr_A=[f(d['VMS A'][k], 3) for k in ('d=1-2', 'd=3-6', 'd=7-14', 'd=15-40', 'd>40', 'other section')], dr_B=[f(d['VMS B'][k], 3) for k in ('d=1-2', 'd=3-6', 'd=7-14', 'd=15-40', 'd>40', 'other section')],
         dr_tw_A=f(d['markov3+drift A']['d=1-2'], 3), dr_tw_A40=f(d['markov3+drift A']['d>40'], 3), dr_la=[f(d['latin (chunk) A'][k], 3) for k in ('d=1-2', 'd=3-6', 'd=7-14', 'd=15-40', 'd>40')])
hv = N['hand_vs_section']; hd = N['hand_by_distance']
v.update(hv_B_ss=f(hv['B same sect same hand']['jsd']), hv_B_sd=f(hv['B same sect diff hand']['jsd']), hv_B_ds=f(hv['B diff sect same hand']['jsd']), hv_B_dd=f(hv['B diff sect diff hand']['jsd']),
         hd_same6=f(hd['B-H']['bins']['d<=6 same hand']['jsd']), hd_diff6=f(hd['B-H']['bins']['d<=6 diff hand']['jsd']), hd_n_same6=hd['B-H']['bins']['d<=6 same hand']['n'], hd_n_diff6=hd['B-H']['bins']['d<=6 diff hand']['n'],
         hd_same20=f(hd['B-H']['bins']['d>20 same hand']['jsd']), hd_diff20=f(hd['B-H']['bins']['d>20 diff hand']['jsd']), hd_pages=hd['B-H']['pages'], hd_hands=hd['B-H']['hands'], hd_big23=', '.join(f"<i>{a.replace(' ', '_')}</i> ({b:+.2f})" for a, b in eval(hd['bigrams_2_over_3'])[:6]), hd_big32=', '.join(f"<i>{a.replace(' ', '_')}</i> ({b:+.2f})" for a, b in eval(hd['bigrams_3_over_2'])[:6]))
lb = N['labels']['table']
v.update(lb_zod_rec=f(lb['zodiac']['rec']), lb_zod_null=f(lb['zodiac']['null']), lb_zod_tok=lb['zodiac']['tokens'], lb_zod_typ=lb['zodiac']['types'], lb_ph_rec=f(lb['pharma']['rec']), lb_ph_null=f(lb['pharma']['null']), lb_ph_tok=lb['pharma']['tokens'], lb_ph_typ=lb['pharma']['types'],
         lb_as_rec=f(lb['astro']['rec']), lb_as_null=f(lb['astro']['null']), lb_bio_rec=f(lb['biological']['rec']), lb_bio_null=f(lb['biological']['null']), lb_n_multi=N['labels']['zodiac_multi_n'], lb_max_multi=N['labels']['zodiac_multi_max'], lb_zod_types_all=N['labels']['zodiac_types'])
ti = N['text_vs_image']
v.update(ti_A_pages=ti['Herbal-A, hand 1']['pages'], ti_A_pairs=f"{ti['Herbal-A, hand 1']['pairs']:,}", ti_A_r=sgn(ti['A_10000_w']['r']), ti_A_p=f(ti['A_10000_w']['p'], 2), ti_A_rb=sgn(ti['A_10000_b']['r']), ti_A_pb=f(ti['A_10000_b']['p'], 2),
         ti_A_rfol=sgn(ti['Herbal-A, hand 1']['r_fol']), ti_A_pfol=f(ti['Herbal-A, hand 1']['p_fol'], 3), ti_A_img_fol=sgn(ti['Herbal-A, hand 1']['r_img_fol']), ti_A_img_fol_p=f(ti['Herbal-A, hand 1']['p_img_fol'], 3),
         ti_B_pages=ti['Herbal-B (hands 2/3/5)']['pages'], ti_B_r=sgn(ti['Herbal-B (hands 2/3/5)']['r_w']), ti_B_p=f(ti['Herbal-B (hands 2/3/5)']['p_w'], 3), ti_B_strat_r=sgn(ti['B_strat_w']['r']), ti_B_strat_p=f(ti['B_strat_w']['p'], 3),
         ti_B_h2_r=sgn(ti['B_h2_w']['r']), ti_B_h2_p=f(ti['B_h2_w']['p'], 2), ti_B_h2_n=ti['B_h2_w']['n'], ti_B_same_r=sgn(ti['B_same_w']['r']), ti_B_same_p=f(ti['B_same_w']['p'], 2),
         ti_mean_words=ti['mean_words'], pc5_r=sgn(ti['positive_control'][5]['r']), pc5_p=f(ti['positive_control'][5]['p'], 2), pc10_r=sgn(ti['positive_control'][10]['r']), pc10_p=f(ti['positive_control'][10]['p'], 3), pc20_r=sgn(ti['positive_control'][20]['r']), pc20_p=f(ti['positive_control'][20]['p'], 3),
         ti_feat_pmin=f(min(x['p'] for x in ti['features'].values()), 2), pc10_share=pct(10 / (ti['mean_words'] + 10), 0))
sw = N['section_within_hand']
v.update(sw1_maj=f(sw['1']['majority'], 2), sw1_w=f(sw['1']['rows'][0]['words'], 2), sw1_w15=f(sw['1']['rows'][15]['words'], 2), sw1_b=f(sw['1']['rows'][0]['bigrams'], 2), sw1_b15=f(sw['1']['rows'][15]['bigrams'], 2),
         sw2_maj=f(sw['2']['majority'], 2), sw2_w=f(sw['2']['rows'][0]['words'], 2), sw2_w15=f(sw['2']['rows'][15]['words'], 2), sw2_b=f(sw['2']['rows'][0]['bigrams'], 2), sw2_b15=f(sw['2']['rows'][15]['bigrams'], 2), sw2_f=f(sw['2']['rows'][0]['folio'], 2), sw2_f15=f(sw['2']['rows'][15]['folio'], 2), sw2_n15=sw['2']['rows'][15]['n'],
         sw3_maj=f(sw['3']['majority'], 2), sw3_w=f(sw['3']['rows'][0]['words'], 2), sw3_b=f(sw['3']['rows'][0]['bigrams'], 2))
J = N['jack']
v.update(jk={k: (f(J['point'][k]), f(J['se'][k])) for k in J['point']}, jk_n=len(J['quires']))
vt = N['vertical']
v.update(vt_prev=f(vt['prev word']['p1']), vt_above=f(vt['word above (same index)']['p1']), vt_page=f(vt['random same page']['p1']), vt_lang=f(vt['random same lang']['p1']), vt_min3=f(vt['word above (i-1..i+1, min)']['p1']), vt_min3r=f(vt['min over 3 random same page']['p1']))
ag = N['agreement']['VMS comma=join']
v.update(ag_min=f(min(ag[k]['ratio'] for k in ('first1', 'first2', 'last1', 'last2', 'last3', 'identical')), 2), ag_max=f(max(ag[k]['ratio'] for k in ('first1', 'first2', 'last1', 'last2', 'last3', 'identical')), 2),
         ag_la_last1=f(N['agreement']['Latin']['last1']['ratio'], 2), ag_it_last1=f(N['agreement']['Italian']['last1']['ratio'], 2), ag_la_ident=f(N['agreement']['Latin']['identical']['ratio'], 2), ag_de_ident=f(N['agreement']['German']['identical']['ratio'], 2), ag_it_ident=f(N['agreement']['Italian']['identical']['ratio'], 2), ag_he_ident=f(N['agreement']['Hebrew']['identical']['ratio'], 2))
dr = N['direction']; v.update(dir_n=dr['n_all'], dir_share=f(dr['share_directional'], 2), dir_maxz=f(max(float(z) for *_, z in dr['top']), 1), dir_q=[x for x in dr['top'] if x[0].startswith('ins q')][0] if any(x[0].startswith('ins q') for x in dr['top']) else None)
rp = N['repeats']; v.update(rep_vms=pct(rp['vms'], 2), rep_de=pct(rp['de_faust'], 2), rep_it=pct(rp['it_dante'], 2), rep_la=pct(rp['la_caesar'], 2))
cc = N['comma_counts']; v.update(comma=f"{cc['comma']:,}", dot=f"{cc['dot']:,}")
bp = N['bpe']; v.update(bpe_vms80=f(bp['VMS'][-1]['ratio'], 2), bpe_vms80_units=bp['VMS'][-1]['units'], bpe_vms0=f(bp['VMS'][0]['ratio'], 2),
                        bpe_lang_min=f(min(x['ratio'] for k in ('de', 'it', 'la', 'he') for x in bp[k]), 2), bpe_lang_max=f(max(x['ratio'] for k in ('de', 'it', 'la', 'he') for x in bp[k]), 2))
ps = N['psim']; v.update(psim_line=f(ps['line']), psim_page=f(ps['page']), psim_lang=f(ps['lang']))
v['date'] = datetime.date.today().strftime('%d %B %Y')

# ---------------------------------------------------------------- tables (HTML)
def table(header, rows, caption=None, cls='', note=None, widths=None):
    h = ('<p class="cap">' + caption + '</p>') if caption else ''
    h += '<table class="tab ' + cls + '">'
    h += '<tr>' + ''.join('<th>' + x + '</th>' for x in header) + '</tr>'
    for row in rows: h += '<tr>' + ''.join('<td>' + str(x) + '</td>' for x in row) + '</tr>'
    h += '</table>'
    if note: h += '<p class="tabnote">' + note + '</p>'
    return h
T = {}
names = {'VMS all (P)': 'Voynich, paragraph text', 'VMS Currier A': '&nbsp;&nbsp;Currier A', 'VMS Currier B': '&nbsp;&nbsp;Currier B', 'la_caesar (chunk)': 'Latin (Caesar)', 'de_faust (chunk)': 'German (Faust)', 'it_dante (chunk)': 'Italian (Dante)', 'en_tolstoy (chunk)': 'English (War and Peace)', 'he_genesis': 'Hebrew (Genesis, consonantal)'}
T['basic'] = table(['Corpus', 'Tokens', 'Types', 'TTR', 'Hapax', 'Mean length', 'h<sub>1</sub>', 'h<sub>2</sub>', 'h<sub>2</sub>/h<sub>1</sub>', 'Zipf slope'],
                   [[names[k], f"{b[k]['tokens']:,}", f"{b[k]['types']:,}", f(b[k]['ttr']), f(b[k]['hapax'], 2), f(b[k]['wlen'], 2), f(b[k]['h1'], 2), f(b[k]['h2'], 2), f(b[k]['h2'] / b[k]['h1'], 2), f(b[k]['zipf'], 2)] for k in names],
                   caption='Table 1. Basic token- and glyph-level statistics. Reference corpora are contiguous chunks matched to the Voynich token count (Hebrew: whole text). h<sub>1</sub> = unigram entropy, h<sub>2</sub> = conditional entropy given the previous symbol (bits per symbol, space included). Zipf slope: log-log slope over the 200 most frequent types.')
pn = {'VMS c=jn': 'Voynich (all)', 'VMSA c=jn': '&nbsp;&nbsp;Currier A', 'VMSB c=jn': '&nbsp;&nbsp;Currier B', 'VMS c=sp': '&nbsp;&nbsp;all, uncertain spaces as spaces', 'Latin': 'Latin', 'Italian': 'Italian', 'German': 'German', 'Hebrew': 'Hebrew'}
T['proj'] = table(['Corpus', 'token &rarr; token', 'last glyph &rarr; first glyph', 'last two &rarr; first two', 'last glyph &rarr; token', 'token &rarr; first glyph'],
                  [[pn[k], f(p[k]['word']), f(p[k]['l1f1']), f(p[k]['l2f2']), f(p[k]['l1w']), f(p[k]['wf1'])] for k in pn],
                  caption='Table 2. Excess mutual information (bits) between adjacent tokens inside lines, for different projections of the token pair, relative to a within-line permutation null with identical marginals. Line-initial and line-final tokens are excluded. Reference corpora are cut into the Voynich line-length distribution.')
lun = {'VMS none': 'Voynich (tokens as transcribed)', 'VMS light': '&nbsp;&nbsp;variant glyphs collapsed', 'VMS-A light': '&nbsp;&nbsp;Currier A, collapsed', 'VMS-B light': '&nbsp;&nbsp;Currier B, collapsed', 'Latin': 'Latin', 'Italian': 'Italian', 'German': 'German'}
T['lineunit'] = table(['Corpus', 'n pairs', 'across line break', 'adjacent, same n', 'adjacent inner, same n', 'across, distance 3', 'within, distance 3'],
                      [[lun[k], f"{lu[k]['n']:,}", f(lu[k]['across']), f(lu[k]['within']) + ' &plusmn; ' + f(lu[k]['within_sd']), f(lu[k]['inner']) + ' &plusmn; ' + f(lu[k]['inner_sd']), f(lu[k]['across_d3']), f(lu[k]['within_d3']) + ' &plusmn; ' + f(lu[k]['within_d3_sd'])] for k in lun],
                      caption='Table 3. Excess mutual information (bits) for the pair (last token of line k, first token of line k+1) within paragraphs, compared with adjacent within-line pairs subsampled to the same n (mean &plusmn; s.d. over 8 subsamples). Reference corpora were cut into lines and paragraphs with the Voynich length distributions.')
spn = {'VMS c=jn': 'Voynich', 'VMS-A c=jn': '&nbsp;&nbsp;Currier A', 'VMS-B c=jn': '&nbsp;&nbsp;Currier B', 'Latin': 'Latin', 'Italian': 'Italian', 'German': 'German', 'Hebrew': 'Hebrew', 'Latin rule-spaced': 'Latin, spaces removed and re-inserted by a glyph rule'}
T['spaces'] = table(['Corpus', 'boundary rate', 'gain, k = 1', 'F<sub>1</sub>, k = 1', 'gain, k = 2', 'F<sub>1</sub>, k = 2', 'gain, k = 3'],
                    [[spn[k], f(s[k][min(s[k])]['rate']), pct(s[k][1]['gain']) if 1 in s[k] else '&ndash;', f(s[k][1]['F1'], 2) if 1 in s[k] else '&ndash;', pct(s[k][2]['gain']), f(s[k][2]['F1'], 2), pct(s[k][3]['gain']) if 3 in s[k] else '&ndash;'] for k in spn],
                    caption='Table 4. Predictability of token boundaries from k glyphs on each side (model fitted on half the lines, evaluated on the other half). Gain = 1 &minus; H(boundary | context)/H(boundary). F<sub>1</sub> for predicting a boundary at threshold 0.5.')
lxn = {'VMS': 'Voynich', 'VMS A': '&nbsp;&nbsp;Currier A', 'VMS B': '&nbsp;&nbsp;Currier B', 'Latin': 'Latin', 'German': 'German', 'Italian': 'Italian', 'Hebrew': 'Hebrew', 'Latin rule msty': 'Latin, rule-spaced', 'Latin bisyl': 'Latin, syllable pairs', 'Latin 3-chunks': 'Latin, 3-letter chunks'}
T['lexicon'] = table(['Corpus', 'real tokens attested', 'synthetic tokens attested', 'real types attested', 'synthetic types attested', 'bits/glyph real', 'bits/glyph synthetic'],
                     [[lxn[k], f(lx[k][2]['tok_real'], 2), f(lx[k][2]['tok_synth'], 2), f(lx[k][2]['typ_real'], 2), f(lx[k][2]['typ_synth'], 2), f(lx[k][2]['bits_real'], 2), f(lx[k][2]['bits_synth'], 2)] for k in lxn],
                     caption='Table 5. Lexicon test. A within-token glyph model with two glyphs of context is fitted on a random half of the tokens; the share of held-out real tokens (types) whose string occurs in the training half is compared with the same share for tokens sampled from the model.')
epn = {'VMS all': 'Voynich', 'VMS A': '&nbsp;&nbsp;Currier A', 'VMS B': '&nbsp;&nbsp;Currier B', 'Latin': 'Latin', 'Italian': 'Italian', 'German': 'German', 'Hebrew': 'Hebrew', 'Latin rule-spaced': 'Latin, rule-spaced'}
T['entropy'] = table(['Corpus', 'h(1)', 'h(2)', 'h(3)', 'h(4)', 'h(5)', 'h(3)&minus;twin', 'h(4)&minus;twin', 'h(5)&minus;twin', 'lzma', 'lzma twin'],
                     [[epn[k]] + [f(x, 2) for x in ep[k]['real']] + [sgn(ep[k]['real'][i] - tw(k)['h'][i], 2) for i in (2, 3, 4)] + [f(ep[k]['lzma'], 2), f(tw(k)['lzma'], 2)] for k in epn],
                     caption='Table 6. Conditional entropy h(k) = H(x | k previous symbols) of the glyph stream (space as a symbol, lines as separate strings), and differences to a synthetic twin sampled from the order-3 model fitted to the same corpus (same number and length of lines). lzma: compressed bits per symbol.')
mcols = [('edge_mi', 'edge MI', 3), ('token_mi', 'token MI', 3), ('break_mi', 'line-break MI', 3), ('space_gain', 'space gain', 'pct'), ('hapax', 'hapax', 2), ('zipf', 'Zipf', 2), ('lex_real', 'attested real', 2), ('lex_synth', 'attested synth.', 2), ('h2', 'h(2)', 2), ('h4', 'h(4)', 2), ('lzma_resid', 'residual', 'sgn'), ('page_mi', 'I(token; page)', 3)]
mrows = [('VMS', 'Voynich (ZL3b)'), ('markov3+drift', 'Glyph automaton, order 3, section drift'), ('markov4+drift', 'Glyph automaton, order 4, section drift'), ('hier o4 lam0.5', 'Glyph automaton, order 4, page drift (&lambda; = 0.5)'),
         ('latin', 'Latin, running text'), ('latin rule-sp', 'Latin, rule-spaced'), ('latin indep lines', 'Latin, one independent sentence per line'), ('rugg grille', 'Table-and-grille generator (after Rugg)'), ('timm-schinner v2', 'Copy-and-modify generator (after Timm and Schinner)'),
         ('verbose+indep', 'Verbose cipher, fixed homophone choice'), ('autokey 1g/letter', 'Ciphertext-feedback substitution, 1 glyph/letter'), ('autokey 2g/letter', 'Ciphertext-feedback substitution, 2 glyphs/letter'),
         ('naibbe indep, card/letter', 'Naibbe cipher, Latin, independent lines'), ('naibbe running', 'Naibbe cipher, Latin, running text'), ('naibbe running Italian', 'Naibbe cipher, Italian, running text'),
         ('naibbe stateful w=0.6 c=0.15', 'Naibbe, state-dependent table choice, w = 0.6'), ('naibbe stateful w=0.9 c=0.15', 'Naibbe, state-dependent, w = 0.9'), ('naibbe stateful w=1.0 c=0.05', 'Naibbe, state-dependent, w = 1.0')]
def mcell(r, k, d):
    x = r.get(k, float('nan'))
    return pct(x) if d == 'pct' else (sgn(x) if d == 'sgn' else f(x, d))
T['mech'] = table(['Mechanism'] + [c[1] for c in mcols], [[lab] + [mcell(m[k], c[0], c[2]) for c in mcols] for k, lab in mrows], cls='small',
                  caption='Table 7. Mechanism battery. All generators produce text in exactly the line and token shape of the Voynich paragraph text. Edge MI and token MI: excess over within-line permutation; line-break MI: (last, first) pair across line breaks; residual: lzma bits per glyph of the text minus that of an order-3 section-drift twin fitted to the same text (negative = redundancy beyond the automaton). The page-drift automaton is fitted in-sample (see text).')
rbn = [('ZL3b jn', 'Zandbergen&ndash;Landini, uncertain spaces joined (baseline)'), ('ZL3b sp', 'Zandbergen&ndash;Landini, uncertain spaces as spaces'), ('IT2a jn', 'Takahashi')]
T['transcr'] = table(['Transcription', 'tokens', 'types', 'edge MI', 'token MI', 'line-break MI', 'space gain', 'hapax', 'attested real / synth.', 'h(2)', 'h(4)', 'residual', 'I(token; page)'],
                     [[lab, f"{t[k]['tokens']:,}", f"{t[k]['types']:,}", f(t[k]['edge']), f(t[k]['token']), f(t[k]['brk']), pct(t[k]['space']), f(t[k]['hapax'], 2), f(t[k]['lex_real'], 2) + ' / ' + f(t[k]['lex_synth'], 2), f(t[k]['h2'], 2), f(t[k]['h4'], 2), sgn(t[k]['resid']), f(t[k]['page'])] for k, lab in rbn], cls='small',
                     caption='Table 8. Robustness to transcription and to the treatment of uncertain spaces.')
rrn = [('held-out real (even pages)', 'Held-out real pages (even)'), ('twin from odd-page model', 'Twin sampled from the odd-page model'), ('hand 1 (112 pages)', 'Hand 1 (112 pages)'), ('hand 2 (46 pages)', 'Hand 2 (46 pages)'), ('hand 3 (31 pages)', 'Hand 3 (31 pages)'), ('Currier A', 'Currier A'), ('Currier B', 'Currier B')]
T['robust'] = table(['Subset', 'edge MI', 'token MI', 'line-break MI', 'space gain', 'hapax', 'Zipf', 'attested real / synth.', 'h(2)', 'h(4)', 'I(token; page)'],
                    [[lab, f(r[k]['edge']), f(r[k]['token']), f(r[k]['brk']), pct(r[k]['space']), f(r[k]['hapax'], 2), f(r[k]['zipf'], 2), f(r[k]['lex_real'], 2) + ' / ' + f(r[k]['lex_synth'], 2), f(r[k]['h2'], 2), f(r[k]['h4'], 2), f(r[k]['page'])] for k, lab in rrn], cls='small',
                    caption='Table 9. Out-of-sample comparison (automaton fitted per section on the odd-numbered pages, evaluated on the even-numbered pages) and the battery restricted to single scribal hands and to the two Currier languages.')
T['jack'] = table(['Statistic', 'estimate', 'jackknife s.e.', '95% interval'],
                  [[lab, f(J['point'][k]), f(J['se'][k]), f(J['ci95'][k][0]) + ' to ' + f(J['ci95'][k][1])] for k, lab in [('edge_mi', 'edge MI'), ('token_mi', 'token MI'), ('break_mi', 'line-break MI'), ('adj_mi_same_n', 'adjacent MI at the line-break n'), ('space_gain', 'space gain (k = 1)'), ('hapax', 'hapax share'), ('zipf', 'Zipf slope'), ('lex_real', 'attested, real'), ('lex_synth', 'attested, synthetic'), ('lex_gap', 'lexicon gap (real &minus; synthetic)'), ('h2', 'h(2)'), ('h4', 'h(4)')]],
                  caption=f'Table 10. Leave-one-quire-out jackknife standard errors for the core Voynich statistics ({len(J["quires"])} quires).')
dcols = ['d = 1&ndash;2', '3&ndash;6', '7&ndash;14', '15&ndash;40', '&gt; 40', 'other section']
T['drift'] = table(['Pages'] + dcols, [[lab] + [f(d[k][c], 3) for c in ('d=1-2', 'd=3-6', 'd=7-14', 'd=15-40', 'd>40', 'other section')] for k, lab in [('VMS A', 'Voynich, Currier A'), ('VMS B', 'Voynich, Currier B'), ('markov3+drift A', 'Section-drift twin, A'), ('markov3+drift B', 'Section-drift twin, B'), ('latin (chunk) A', 'Latin in book order (chunked like A)')]],
                   caption='Table 11. Mean Jensen&ndash;Shannon divergence between the glyph-bigram distributions of two pages (450-glyph samples) as a function of their folio distance, within the same section and Currier language.')
T['hand'] = table(['Pairs', 'same section, same hand', 'same section, different hand', 'different section, same hand', 'different section, different hand'],
                  [['Currier B, all sections', f(hv['B same sect same hand']['jsd']), f(hv['B same sect diff hand']['jsd']), f(hv['B diff sect same hand']['jsd']), f(hv['B diff sect diff hand']['jsd'])],
                   ['Herbal-B, folio distance &le; 6 pages', f(hd['B-H']['bins']['d<=6 same hand']['jsd']), f(hd['B-H']['bins']['d<=6 diff hand']['jsd']), '&ndash;', '&ndash;'],
                   ['Herbal-B, folio distance &gt; 20 pages', f(hd['B-H']['bins']['d>20 same hand']['jsd']), f(hd['B-H']['bins']['d>20 diff hand']['jsd']), '&ndash;', '&ndash;']],
                  caption='Table 12. Mean Jensen&ndash;Shannon divergence between pages grouped by scribal hand (palaeographic assignment of Davis 2020 as recorded in the ZL metadata) and illustration section.')
T['labels'] = table(['Section', 'pages', 'label tokens', 'label types', 'share recurring on another page', 'null: text tokens of the same pages'],
                    [[lab, lb[k]['pages'], lb[k]['tokens'], lb[k]['types'], f(lb[k]['rec']), f(lb[k]['null'])] for k, lab in [('zodiac', 'Zodiac'), ('astro', 'Astronomical'), ('pharma', 'Pharmaceutical'), ('biological', 'Biological'), ('cosmo', 'Cosmological')]],
                    caption='Table 13. Recurrence of label tokens across the pages of a section, compared with equally many randomly drawn paragraph-text tokens from the same pages (mean of 20 draws).')
T['tvi'] = table(['Page set', 'text representation', 'Mantel r', 'p (permutation)', 'text vs folio distance r (p)'],
                 [['Herbal-A, hand 1 (' + str(ti['Herbal-A, hand 1']['pages']) + ' pages)', 'token frequencies', sgn(ti['A_10000_w']['r']), f(ti['A_10000_w']['p'], 2), sgn(ti['Herbal-A, hand 1']['r_fol']) + ' (' + f(ti['Herbal-A, hand 1']['p_fol'], 3) + ')'],
                  ['', 'glyph-bigram frequencies', sgn(ti['A_10000_b']['r']), f(ti['A_10000_b']['p'], 2), '&ndash;'],
                  ['Herbal-B, hands 2 and 5 (' + str(ti['Herbal-B (hands 2/3/5)']['pages']) + ' pages), unstratified', 'token frequencies', sgn(ti['Herbal-B (hands 2/3/5)']['r_w']), f(ti['Herbal-B (hands 2/3/5)']['p_w'], 3), sgn(ti['Herbal-B (hands 2/3/5)']['r_fol']) + ' (' + f(ti['Herbal-B (hands 2/3/5)']['p_fol'], 3) + ')'],
                  ['&nbsp;&nbsp;permutation within hand', 'token frequencies', sgn(ti['B_strat_w']['r']), f(ti['B_strat_w']['p'], 3), '&ndash;'],
                  ['&nbsp;&nbsp;same-hand pairs only', 'token frequencies', sgn(ti['B_same_w']['r']), f(ti['B_same_w']['p'], 2), '&ndash;'],
                  ['&nbsp;&nbsp;hand 2 only (' + str(ti['B_h2_w']['n']) + ' pages)', 'token frequencies', sgn(ti['B_h2_w']['r']), f(ti['B_h2_w']['p'], 2), '&ndash;'],
                  ['&nbsp;&nbsp;hand 2 only', 'glyph-bigram frequencies', sgn(ti['B_h2_b']['r']), f(ti['B_h2_b']['p'], 2), '&ndash;']],
                 caption='Table 14. Mantel tests between text distance and illustration-feature distance across herbal pages (pairs closer than 3 folios excluded).')
T['pc'] = table(['tokens added per page', 'Mantel r', 'p'], [[k, sgn(ti['positive_control'][k]['r']), f(ti['positive_control'][k]['p'], 3)] for k in sorted(ti['positive_control'])],
                caption=f"Table 15. Sensitivity control: image-determined pseudo-tokens added to each Herbal-A page (mean page length {ti['mean_words']} tokens).")
T['sect'] = table(['Hand (sections)', 'majority rate', 'excluded radius (folios)', 'tokens', 'glyph bigrams', 'nearest folio only', 'n'],
                  sum([[[lab if i == 0 else '', f(sw[h]['majority'], 2), rad, f(sw[h]['rows'][rad]['words'], 2), f(sw[h]['rows'][rad]['bigrams'], 2), f(sw[h]['rows'][rad]['folio'], 2), sw[h]['rows'][rad]['n']] for i, rad in enumerate(sorted(sw[h]['rows']))] for h, lab in [('1', 'Hand 1 (herbal vs pharmaceutical)'), ('2', 'Hand 2 (biological vs herbal)'), ('3', 'Hand 3 (stars vs herbal)')]], []),
                  caption='Table 16. Leave-one-page-out nearest-centroid prediction of the illustration section within a scribal hand, from token frequencies and from glyph-bigram frequencies, excluding pages within the given folio radius; compared with the majority rate and with predicting from the nearest remaining folio.')
# supplement tables
agn = {'VMS comma=join': 'Voynich', 'VMSA comma=join': '&nbsp;&nbsp;Currier A', 'VMSB comma=join': '&nbsp;&nbsp;Currier B', 'Latin': 'Latin', 'Italian': 'Italian', 'German': 'German', 'Hebrew': 'Hebrew'}
AG = N['agreement']
T['agree'] = table(['Corpus', 'n pairs', 'first glyph', 'first two', 'last glyph', 'last two', 'last three', 'identical'],
                   [[agn[k], f"{AG[k]['n']:,}"] + [f(AG[k][c]['obs'], 3) + ' / ' + f(AG[k][c]['null'], 3) + ' = ' + f(AG[k][c]['ratio'], 2) for c in ('first1', 'first2', 'last1', 'last2', 'last3', 'identical')] for k in agn],
                   caption='Table S1. Share of adjacent inner tokens that share the given feature, observed / within-line permutation null = ratio.', cls='small')
T['direction'] = table(['edit a &rarr; b', 'count a &rarr; b', 'count b &rarr; a', 'z'], [[x[0], x[1], x[2], x[3]] for x in dr['top']],
                       caption=f"Table S2. Single-glyph edits between adjacent inner tokens at edit distance 1 ({dr['n_all']} pairs), forward versus inverse counts; z = (n<sub>ab</sub> &minus; n<sub>ba</sub>)/&radic;(n<sub>ab</sub> + n<sub>ba</sub>). Share of pairs in edits whose inverse is less than half as frequent: {f(dr['share_directional'], 2)}.")
T['vertical'] = table(['Relation', 'pairs', 'mean edit distance', 'P(identical)', 'P(ED &le; 1)', 'P(ED &le; 2)'],
                      [[k, f"{vt[k]['n']:,}", f(vt[k]['meanED'], 2), f(vt[k]['p0']), f(vt[k]['p1']), f(vt[k]['p2'])] for k in vt],
                      caption='Table S3. Similarity of a token to candidate copy sources (Timm and Schinner 2020) and to controls.')
T['bpe'] = table(['merges'] + [k for k in ('VMS', 'de', 'it', 'la', 'he')], [[row['merges']] + [f(bp[k][i]['ratio'], 2) + ' (' + str(bp[k][i]['units']) + ')' for k in ('VMS', 'de', 'it', 'la', 'he')] for i, row in enumerate(bp['VMS'])],
                 caption='Table S4. h<sub>2</sub>/h<sub>1</sub> after a given number of byte-pair merges (inventory size in parentheses).')
T['pmi'] = table(['Corpus', 'total excess', 'ED = 0', 'ED = 1', 'ED = 2', 'ED &ge; 3'], [[k, f(g[k]['total']), f(g[k]['ed0']), f(g[k]['ed1']), f(g[k]['ed2']), f(g[k]['ed3'])] for k in g],
                 caption='Table S5. Decomposition of the adjacent-token excess MI (global marginal-preserving null) by edit distance between the two tokens.')
T['pos'] = table(['Position in line', 'Voynich I(token; page)', 'Voynich types/n', 'Latin I(token; page)', 'Italian I(token; page)'],
                 [[k, f(ed['VMS raw']['pos'][k]['mi']), f(ed['VMS raw']['pos'][k]['ttr']), f(ed['Latin (chunked)']['pos'][k]['mi']), f(ed['Italian (chunked)']['pos'][k]['mi'])] for k in ('first', 'second', 'middle', 'penult', 'last')],
                 caption='Table S6. Page specificity of tokens by position in the line (equal n per position).')
T['combo'] = table(['Pair of consecutive lines', 'Voynich', 'Latin', 'Italian'], [[k, f(ed['VMS raw']['combo'][k]['mi']), f(ed['Latin (chunked)']['combo'][k]['mi']), f(ed['Italian (chunked)']['combo'][k]['mi'])] for k in ed['VMS raw']['combo']],
                   caption='Table S7. Excess MI between tokens of consecutive lines of the same page, by position class.')
T['hier'] = table(['Automaton'] + [c[1] for c in mcols], [[k] + [mcell(m[k], c[0], c[2]) for c in mcols] for k in ('hier o3 lam0.5', 'hier o4 lam0.3', 'hier o4 lam0.5', 'hier o4 lam0.7', 'hier o5 lam0.3')], cls='small',
                  caption='Table S8. Page-drift automata: order o, mixing weight &lambda; of page-level counts against section-level counts.')
T['naibbe_var'] = table(['Variant'] + [c[1] for c in mcols], [[k] + [mcell(m[k], c[0], c[2]) for c in mcols] for k in ('naibbe indep, card/letter', 'naibbe indep, card/token', 'naibbe indep, no merge', 'naibbe running', 'naibbe running Italian')], cls='small',
                        caption='Table S9. Naibbe cipher variants: one card per letter or per token; with and without the 3% random space removal; independent sentences per line or running text; Latin or Italian plaintext.')
T['feat'] = table(['Image feature', 'Mantel r (tokens)', 'p'], [[k, sgn(x['r']), f(x['p'], 2)] for k, x in ti['features'].items()], caption='Table S10. Herbal-A: Mantel test for each single image feature.')
T['full'] = table(['Mechanism'] + [k for k in ('tokens', 'types', 'wlen', 'd2_mi', 'adj_mi_same_n', 'break_edge', 'adj_edge_same_n', 'h3', 'lzma', 'h3_resid')], [[k] + [(f(m[k].get(c, float('nan')), 3) if isinstance(m[k].get(c, 0), float) else str(m[k].get(c, ''))) for c in ('tokens', 'types', 'wlen', 'd2_mi', 'adj_mi_same_n', 'break_edge', 'adj_edge_same_n', 'h3', 'lzma', 'h3_resid')] for k in m], cls='small',
                  caption='Table S11. Additional battery columns for all mechanisms (d2_mi: tokens at distance 2, global null; break_edge / adj_edge: glyph-level (last, first) MI across the line break and for adjacent pairs at the same n; h3_resid: h(3) minus twin).')

# ---------------------------------------------------------------- render
env = Environment(loader=FileSystemLoader('paper/templates'), autoescape=False)
CSS = open('paper/templates/style.css').read()
for name in ('main', 'supplement'):
    html = env.get_template(name + '.html').render(v=v, T=T, css=CSS)
    open(f'paper/{"paper" if name == "main" else "supplement"}.html', 'w').write(html)
    story = fitz.Story(html=html, user_css=CSS, archive=fitz.Archive('.'))
    out = f'paper/{"paper" if name == "main" else "supplement"}.pdf'
    writer = fitz.DocumentWriter(out); mediabox = fitz.paper_rect('a4'); where = mediabox + (60, 62, -60, -66)
    more = True; npages = 0
    while more:
        dev = writer.begin_page(mediabox); more, _ = story.place(where); story.draw(dev); writer.end_page(); npages += 1
    writer.close()
    doc = fitz.open(out)
    head = 'Beyer — A local glyph process suffices for the Voynich manuscript text' if name == 'main' else 'Supplementary material'
    for i, page in enumerate(doc):
        page.insert_text((60, 40), head, fontsize=7.5, fontname='helv', color=(0.35, 0.35, 0.35))
        page.insert_text((mediabox.width / 2 - 8, mediabox.height - 36), str(i + 1), fontsize=8.5, fontname='helv')
    doc.save(out + '.tmp', garbage=4, deflate=True, deflate_images=True, deflate_fonts=True)
    doc.close(); os.replace(out + '.tmp', out)
    print(name, 'pages:', npages)
